export const ADD_NEW_PROJECT = 'ADD_NEW_PROJECT';
export const GET_DETAIL_PROJECT = 'GET_DETAIL_PROJECT';

export const SET_DETAIL_PROJECT = 'SET_DETAIL_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';