export const ADD_NEW_TEAM_PROJECT = 'ADD_NEW_TEAM_PROJECT';
export const GET_DETAIL_TEAM_PROJECT = 'GET_DETAIL_TEAM_PROJECT';

export const SET_DETAIL_TEAM_PROJECT = 'SET_DETAIL_TEAM_PROJECT';
export const UPDATE_TEAM_PROJECT = 'UPDATE_TEAM_PROJECT';