export const ADD_NEW_EMPLOYEE = 'ADD_NEW_EMPLOYEE';
export const GET_DETAIL_EMPLOYEE = 'GET_DETAIL_EMPLOYEE';

export const SET_DETAIL_EMPLOYEE = 'SET_DETAIL_EMPLOYEE';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';