export const ADD_NEW_DEPARTMENT = 'ADD_NEW_DEPARTMENT';
export const GET_DETAIL_DEPARTMENT = 'GET_DETAIL_DEPARTMENT';

export const SET_DETAIL_DEPARTMENT = 'SET_DETAIL_DEPARTMENT';
export const UPDATE_DEPARTMENT = 'UPDATE_DEPARTMENT';